---
- name: Include OS Specific setup tasks
  include_tasks: setup-{{ ansible_os_family }}.yml

- ansible.builtin.include_tasks:
    file: security_actions.yml
- ansible.builtin.include_tasks: 
    file: config.yml
- ansible.builtin.include_tasks: 
    file: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
